### ISSUE TITLE
Can't figure out how to get this to work on international howrse with google chrome

### ISSUE THREAD

**Issue by hyrulewarrior13** [demonlexe/HowrseAdvisor#44]
unfortunately it isn;t working for me, I have everything installed and turned on for ap farm

**Comment by demonlexe** [comment]
Hey! That's because the manifest is written to recognize us.howrse.com. 

If you fork the repo and change every instance of "us.howrse" it should work. 

Let me know if that doesn't work :)

**Comment by demonlexe** [comment]
Once you have it working, open a pull request and I can add the international server to the main branch

**Comment by hyrulewarrior13** [comment]
Thank you! I'll see if I can figure out how to do that!

**Comment by demonlexe** [comment]
Following up on this. I'll try to make an account on international and see if there is anything that needs to be fixed other than the URLs.

**Comment by demonlexe** [comment]
Check out the above branch and use that in Chrome. Let me know if you find any issues.
